name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Terraform environment to destroy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod
      confirm_destroy:
        description: Type destroy to confirm
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  TF_IN_AUTOMATION: true

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'destroy'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Terraform working directory
        run: echo "TF_WORKING_DIR=environments/${{ inputs.environment }}" >> "$GITHUB_ENV"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Destroy Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -destroy -out=tfdestroy

      - name: Terraform Destroy Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfdestroy
